### ISSUE TITLE
Results run & archive

### ISSUE THREAD

**Issue by jbousquin** [USEPA/CHAPPIE#107]
Two potential purposes here (may end up as separate tasks):
- Semi-automate updating expected results for testing
- Batch run and archive results on a set schedule (e.g., monthly)

For the first it would deploy (like docs) but as a bot-commit (from [harmonize-wq](https://github.com/USEPA/harmonize-wq/blob/main/.github/workflows/nb_refresh.yml)):
```
- name: commit updated notebook
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
```
The difference being we would want it semi-automated instead of automated, so we'd want it as a PR we'd approve, not auto-merge (I think).

For the second it would run and generate an artifact that we would then need to download to wherever we archive since I think that will be local (if cloud we might be able to deploy to it).
